export const pangolinQuizzes = [
  {
    id: 1,
    question: "Trên thế giới có tất cả bao nhiêu loài tê tê?",
    options: ["6", "7", "8", "9"],
    correctAnswerIndex: 2,
  },
  {
    id: 2,
    question: "Ở châu Á có tất cả bao nhiêu loài tê tê?",
    options: ["3", "4", "5", "7"],
    correctAnswerIndex: 1,
  },
  {
    id: 3,
    question: "Tê tê phân bố ở những châu lục nào trên thế giới?",
    options: [
      "Châu Á, châu Phi",
      "Châu Á, châu Âu",
      "Châu Á, châu Đại Dương",
      "Châu Á, châu Mỹ",
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 4,
    question: "Ở Việt Nam có tất cả bao nhiêu loài tê tê?",
    options: ["0", "1", "2", "3"],
    correctAnswerIndex: 2,
  },
  {
    id: 5,
    question: "Những loài tê tê phân bố ở Việt Nam là:",
    options: [
      "Tê tê bụng đen, tê tê bụng trắng",
      "Tê tê vàng, tê tê Ấn Độ",
      "Tê tê Java, tê tê Temminck",
      "Tê tê vàng, tê tê Java",
    ],
    correctAnswerIndex: 3,
  },
  {
    id: 6,
    question: "Thức ăn của tê tê là:",
    options: ["Nhện, thằn lằn", "Hoa quả, giun dế", "Kiến, mối", "Cỏ, lá cây"],
    correctAnswerIndex: 2,
  },
  {
    id: 7,
    question: "Tê tê thuộc nhóm động vật nào?",
    options: ["Lưỡng cư", "Thú", "Chim", "Bò sát"],
    correctAnswerIndex: 1,
  },
  {
    id: 8,
    question: "Thành phần chính của vảy tê tê là:",
    options: ["Keratin", "Canxi", "Chitin", "Silic"],
    correctAnswerIndex: 0,
  },
  {
    id: 9,
    question: "Tê tê có răng hay không?",
    options: [
      "Có răng nanh sắc",
      "Có răng nhưng nhỏ",
      "Không có răng",
      "Có răng hàm",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 10,
    question: "Tê tê có thể cuộn tròn cơ thể để làm gì?",
    options: ["Giữ nhiệt", "Tự vệ khỏi kẻ thù", "Ngủ", "Giao tiếp"],
    correctAnswerIndex: 1,
  },
  {
    id: 11,
    question: "Thời gian hoạt động chính của tê tê là:",
    options: ["Ban ngày", "Ban đêm", "Cả ngày lẫn đêm", "Tùy mùa"],
    correctAnswerIndex: 1,
  },
  {
    id: 12,
    question: "Vảy tê tê có công dụng chính là gì?",
    options: [
      "Hỗ trợ leo trèo",
      "Giữ nhiệt",
      "Bảo vệ cơ thể khỏi kẻ thù",
      "Giúp di chuyển nhanh",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 13,
    question: "Tê tê sử dụng cơ chế gì để bắt kiến và mối?",
    options: ["Cắn nhanh", "Gặm nhấm", "Hút như vòi", "Dùng lưỡi dính dài"],
    correctAnswerIndex: 3,
  },
  {
    id: 14,
    question: "Tê tê có thuộc nhóm động vật nguy cấp không?",
    options: [
      "Có, bị đe dọa nghiêm trọng",
      "Không, rất phổ biến",
      "Ở mức ít nguy cấp",
      "Không xác định",
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 15,
    question: "Tê tê có thị lực thế nào?",
    options: [
      "Nhìn rất rõ ban đêm",
      "Thị lực yếu, dựa vào khứu giác",
      "Thị lực giống mèo",
      "Mù hoàn toàn",
    ],
    correctAnswerIndex: 1,
  },
  {
    id: 16,
    question: "Tê tê con thường bám vào đâu của mẹ?",
    options: ["Bụng mẹ", "Lưng mẹ", "Đuôi mẹ", "Miệng mẹ"],
    correctAnswerIndex: 2,
  },
  {
    id: 17,
    question: "Mối đe doạ chính của tê tê là gì?",
    options: [
      "Cá sấu",
      "Báo hoa mai",
      "Con người (săn bắt trái phép)",
      "Chim săn mồi",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 18,
    question: "Tê tê khi bị đe dọa thường làm gì?",
    options: [
      "Chạy trốn thật nhanh",
      "Cuộn tròn thành quả bóng",
      "Đào hố ẩn nấp ngay lập tức",
      "Trèo lên cây",
    ],
    correctAnswerIndex: 1,
  },
  {
    id: 19,
    question: "Tê tê thuộc bộ nào trong phân loại động vật?",
    options: ["Bộ ăn kiến", "Bộ Pholidota", "Bộ gặm nhấm", "Bộ thú có túi"],
    correctAnswerIndex: 1,
  },
  {
    id: 20,
    question: "Lưỡi của tê tê có thể dài tới bao nhiêu cm?",
    options: ["40 cm", "20 cm", "10 cm", "70 cm"],
    correctAnswerIndex: 0,
  },
  {
    id: 21,
    question: "Một lứa tê tê thường sinh mấy con?",
    options: ["2 con", "3 con", "5 con", "1 con"],
    correctAnswerIndex: 3,
  },
  {
    id: 22,
    question: "Khứu giác của tê tê như thế nào?",
    options: ["Rất yếu", "Rất phát triển", "Trung bình", "Gần như không có"],
    correctAnswerIndex: 1,
  },
  {
    id: 23,
    question: "Tê tê thuộc nhóm động vật máu nóng hay lạnh?",
    options: ["Máu lạnh", "Máu nóng", "Cả hai", "Tùy môi trường"],
    correctAnswerIndex: 1,
  },
  {
    id: 24,
    question: "Tê tê có thể sống trong loại môi trường nào?",
    options: [
      "Núi băng",
      "Sa mạc nóng",
      "Rừng nhiệt đới và đồng cỏ",
      "Dưới lòng đất sâu 50 m",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 25,
    question: "Tê tê thường làm gì để tìm thức ăn?",
    options: [
      "Leo cây cao",
      "Rình chờ mồi",
      "Đào tổ mối và tổ kiến",
      "Bắt côn trùng bay",
    ],
    correctAnswerIndex: 2,
  },
  {
    id: 26,
    question: "Khi thấy tê tê bị bắt, mình cần làm gì?",
    options: ["Mặc kệ", "Báo với cơ quan chức năng", "Ủng hộ", "Chạy đi"],
    correctAnswerIndex: 1,
  },
  {
    id: 27,
    question: "Khi được mời ăn tê tê, mình cần làm gì?",
    options: ["Ăn", "Cảm ơn", "Chia sẻ", "Từ chối"],
    correctAnswerIndex: 3,
  },
  {
    id: 28,
    question: "Nếu thấy người khác ăn thịt tê tê, sử dụng vảy tê tê bạn sẽ:",
    options: ["Lên án", "Ăn cùng", "Ngưỡng mộ", "Không làm gì"],
    correctAnswerIndex: 0,
  },
  {
    id: 29,
    question: "Loài tê tê nào nhỏ nhất trong 8 loài tê tê trên thế giới?",
    options: ["Tê tê Java", "Tê tê vàng", "Tê tê Ấn Độ", "Tê tê bụng trắng"],
    correctAnswerIndex: 3,
  },
  {
    id: 30,
    question: "Tê tê là loài thú duy nhất có vảy trên thế giới, đúng hay sai?",
    options: ["Đúng", "Sai"],
    correctAnswerIndex: 0,
  },
];
